import logging
import uuid
import base64
from pathlib import Path

logger = logging.getLogger(__name__)

class MediaService:
    """
    Media Service for YPhotoSharing.
    Handles storage of image and video assets generated by agents.
    """

    def __init__(self, storage_dir: str = "example/media"):
        self.storage_dir = Path(storage_dir)
        self.storage_dir.mkdir(parents=True, exist_ok=True)
        logger.info(f"MediaService initialized. Storage: {self.storage_dir}")

    def save_media(self, content_base64: str, extension: str = "jpg") -> str:
        """
        Takes base64 encoded media content, saves it to disk, 
        and returns a stable local URL.
        """
        media_id = str(uuid.uuid4())
        filename = f"{media_id}.{extension}"
        filepath = self.storage_dir / filename
        
        try:
            # If it's actual base64 image data, we would decode it.
            # But if it's a procedural stub URL (like a direct Unsplash link),
            # we can just return it. For this simulation, we'll write a stub file 
            # if base64 is provided, or just return a dummy URL if base64 is "stub".
            
            if content_base64 == "stub" or content_base64.startswith("http"):
                # It's a direct URL or stub
                return content_base64 if content_base64.startswith("http") else f"file:///{filepath.absolute()}"
                
            # Decode and save
            with open(filepath, "wb") as f:
                f.write(base64.b64decode(content_base64))
                
            return f"file:///{filepath.absolute()}"
        except Exception as e:
            logger.error(f"Failed to save media {filename}: {e}")
            return ""
